### ISSUE TITLE
impossible to quit

### ISSUE THREAD

**Issue by enjoyaol** [retsamknaps/aktie#1]
On windows 7 when I close aktie, it restarts.. killing java.exe does the same.
Wtf ?

**Comment by retsamknaps** [comment]
Sry.  That's an attempt to restart if updates get fuddled up.  Unfortunately, the router sometimes barfs when you try to close and then it thinks it needs to restart.  There should be two java instances running though, one for the troublesome wrapper that's making it restart.  If you kill that one it should keep it from restarting.  We will try to fix though.

**Comment by retsamknaps** [comment]
Check i2p return codes.

**Comment by retsamknaps** [comment]
0.1.9 fixes this.  now have an explicit rc for restart on upgrade.

You'll need to download the new aktie.jar as it's in the wrapper code.  An automatic update won't pick it up.  You can simply replace your old aktie.jar in your run directory with the new one and it will take care of it.

Thanks!
