### ISSUE TITLE
Aktie 0.4.5. don't start on Win7 64bit?!  

### ISSUE THREAD

**Issue by EmJotGeh** [retsamknaps/Aktie#41]
Aktie 0.4.4. works fine for me but 0.4.5 don't start? After double click nothing happend.

**Comment by retsamknaps** [comment]
Very odd.  We do some testing on win7.  What version of java are you running?  Can you open a cmd window and try this:
java -version
And let us know your java version

Also you might check what this file has at the end of it:
aktie_run_dir/aktie_node/i2p/wrapper.log
Exceptions are sometimes interesting

**Comment by EmJotGeh** [comment]
Hi,

i'm sorry i should know that the java version is important! 

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

but there is no wrapper.log in this directory!?

thanks

**Comment by EmJotGeh** [comment]
With 0.4.6. i can see the GUI.. but only with "no respond" and i must close the Aktie Window
now on:
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by retsamknaps** [comment]
We'll see if we can try this version of Java on windows 7.

**Comment by EmJotGeh** [comment]
Hi,

0.4.8 works again... maybe the previous Versions too. I start Aktie in a new Folder and it works again without any problems. But now, how can i restore my old profile with my community?

thanks
