### ISSUE TITLE
All the listbox controls are not showing any text

### ISSUE THREAD

**Issue by slothbag** [retsamknaps/Aktie#7]
Although I can see that there is an item present, though no text to read.

I'm on Java 1.8.0, Ubuntu linux.

**Comment by retsamknaps** [comment]
Thank you for your report.

What is the title of the box?  There are two of the left.  The top one should have stuff in it shortly after startup.  While the bottom "memberships" one will only have stuff if you're a member of private communities. 

Can you say what window manager and the java vendor?  We had reports of this before, but we have a hard time reproducing it.

**Comment by slothbag** [comment]
All the list boxes are not working.. the Top left "Community" box, the members box, the Posts box, the files box..

The post preview (textbox) works fine.

WM is standard unity, Java is Oracle v1.8.0_45

**Comment by retsamknaps** [comment]
Thank you.  We will try to reproduce and fix.

**Comment by retsamknaps** [comment]
Repro-ed upgrading to swt 4.5 fixes.  swt 4.5 will be included in 0.2.7.  thank you.
